server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engineerplatform_db
    username: engineerplatform
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.engineerplatform: INFO
  file:
    name: /var/log/engineer-platform/backend.log

app:
  ollama:
    base-url: http://localhost:11434
